image: alpine/latest
packages:
  - cmake
  - glog-dev
  - nlohmann-json
  - boost-dev
  - clang17
  - zstd
sources:
  - https://git.sr.ht/~ragreener1/contagent
triggers:
  - action: email
    condition: failure
    to: ~ragreener1/public-inbox@lists.sr.ht
tasks:
  - setup: |
      cd contagent
      CC=clang CXX=clang++ cmake -S . -B builddir -G Ninja
  - compile: |
      cd contagent
      ninja -C builddir
