image: debian/stable
packages:
  - meson
  - libglib2.0-dev
  - pkg-config
sources:
  - git@git.sr.ht:~ragreener1/contagent
triggers:
  - action: email
    condition: failure
    to: ~ragreener1/contagent-devel@lists.sr.ht
secrets:
  - 60919306-69a2-4760-8001-1a12c14454ab
tasks:
  - setup: |
      cd contagent
      meson setup builddir
  - compile: |
      cd contagent
      ninja -C builddir