image: debian/stable
packages:
  - meson
  - libgoogle-glog-dev
  - nlohmann-json3-dev
  - libboost-all-dev
  - pkg-config
sources:
  - git@git.sr.ht:~ragreener1/contagent
secrets:
  - 60919306-69a2-4760-8001-1a12c14454ab
tasks:
  - setup: |
      cd contagent
      meson setup builddir
  - compile: |
      cd contagent
      ninja -C builddir
