image: debian/stable
packages:
  - meson
  - libglib2.0-dev
  - pkg-config
sources:
  - https://git.sr.ht/~ragreener1/contagent
triggers:
  - action: email
    condition: failure
    to: ~ragreener1/public-inbox@lists.sr.ht
tasks:
  - setup: |
      cd contagent
      meson setup builddir
  - compile: |
      cd contagent
      ninja -C builddir