FROM mcr.microsoft.com/devcontainers/base:ubuntu-24.04

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y libboost-all-dev \
        libgoogle-glog-dev nlohmann-json3-dev ninja-build clang cmake pkg-config \
        libzstd-dev